version: '3.6'

services:
  broker:
    image: aws-openid-broker
    container_name: aws-openid-broker
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    ports:
      - 5000:5000
